# -*- coding: utf-8 -*-
"""siggenpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKL25dKplFNGKLD1MA6XmB_wzvPSKMOv
"""

import numpy as np
import scipy.signal as sig
from matplotlib import pyplot as plt
import seaborn as sns

class discrete_time():

  def disc_plot(x, y, title, func_name='f[n]'):
    plt.figure(figsize=(8,5))
    plt.title(title)
    plt.xlabel("n")
    plt.ylabel(func_name)
    plt.stem(x,y,use_line_collection=True)
    plt.grid()
    return plt.show()

  def unit_impulse(min, max):
    N = np.arange(min, max+1)
    delta_sig = sig.unit_impulse(N.shape, idx='mid')
    return delta_sig
  
  def unit_step(min, max):
    N = np.arange(min, max+1)
    unit_step = np.ones(N.shape)
    unit_step[N<0]=0
    return unit_step

  def ramp_signal(min, max):
    N = np.arange(min, max+1)
    ramp_step = N * discrete_time.unit_step(min, max)
    return ramp_step

  def exponential_decay(min, max, alpha):
    N = np.arange(min, max+1)
    unit_step = np.ones(N.shape)
    unit_step[N<0]=0
    exp_decay = (alpha**N) * unit_step
    return exp_decay

  def exponential_growth(min, max, alpha):
    N = np.arange(min, max+1)
    unit_step = np.ones(N.shape)
    unit_step[N<0]=0
    exp_growth = (N**alpha) * unit_step
    return exp_growth

  def leaky_ReLU(min, max, leak):
    N = np.arange(min, max)
    unit_step = np.ones(N.shape)
    leaky_relu = N * unit_step
    leaky_relu[N<0] *= leak
    return leaky_relu
  
  def ELU_signal(min, max, leak):
    N = np.arange(min, max)
    unit_step = np.ones(N.shape)
    elu = N * unit_step
    elu[N<0]=leak
    return elu
  
  def sigmoid_signal(min, max):
    x = np.arange(min,max+1)
    s = 1 / (1 + np.exp((-x)))
    return s

  def generate_signal(signal, min, max, alpha=0.01):
    if signal == 'impulse':
      return discrete_time.disc_plot(np.arange(min,max+1), discrete_time.unit_impulse(min, max), 'Impulse Signal')
    elif signal == 'unit-step':
      return discrete_time.disc_plot(np.arange(min,max+1), discrete_time.unit_step(min, max), 'Unit-Step Signal')
    elif signal == 'ramp':
      return discrete_time.disc_plot(np.arange(min,max+1), discrete_time.ramp_signal(min, max), 'Ramp Signal')
    elif signal == 'decay':
      return discrete_time.disc_plot(np.arange(min,max+1), discrete_time.exponential_decay(min, max, alpha), 'Exponential Decay Signal')
    elif signal == 'growth':
      return discrete_time.disc_plot(np.arange(min,max+1), discrete_time.exponential_growth(min, max, alpha), 'Exponential Growth Signal')
    elif signal == 'leaky':
      return discrete_time.disc_plot(np.arange(min,max), discrete_time.leaky_ReLU(min, max, alpha), 'Leaky Signal')
    elif signal == 'elu':
      return discrete_time.disc_plot(np.arange(min,max), discrete_time.ELU_signal(min, max, alpha), 'ELU Signal')
    elif signal == 'sigmoid':
      return discrete_time.disc_plot(np.arange(min,max+1), discrete_time.sigmoid_signal(min, max), 'Sigmoid Signal')
    else:
      print("Invalid signal input")